### ISSUE TITLE
"INFO Loaded 0 SomaFM Channels" on Mopidy Startup

### ISSUE THREAD

**Issue by KitN** [AlexandrePTJ/mopidy-somafm#14]
I have installed and configured the extension according to the documentation, but Mopidy claims not to have loaded any channels and I cannot see any playlists in ncmpdpp.

https://gist.github.com/KitN/a8cf5e7be86186dcfd83

See the link to the mopidy log above.

**Comment by KitN** [comment]
Changing my configuration from
```
[somafm]
encoding = aac
quality = fast
```
to
```
[somafm]
encoding = mp3
quality = fast
```
fixed the problem, but I don't know why.

**Comment by AlexandrePTJ** [comment]
The reason is that Soma FM do not provides every combination of encoding/quality.
If you want `fast` quality then format is either `mp3` or `aacp`

**Comment by adamcik** [comment]
Perhaps add a hint in the log message or just in the documentation in case other people run into this?

**Comment by AlexandrePTJ** [comment]
Yes, you are faster than my documentation writing skill :)

2015-06-03 10:25 GMT+02:00 Thomas Adamcik <notifications@github.com>:

> Perhaps add a hint in the log message or just in the documentation in case
> other people run into this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlexandrePTJ/mopidy-somafm/issues/14#issuecomment-108245435>
> .
>



-- 
Cordialement,
Alexandre Petitjean.
