### ISSUE TITLE
Add mopidy-somafm to apt.mopidy.com repository

### ISSUE THREAD

**Issue by PanderMusubi** [AlexandrePTJ/mopidy-somafm#16]
Please add mopidy-somafm to apt.mopidy.com repository so it can be installed with `apt-get install mopidy-somafm`

**Comment by AlexandrePTJ** [comment]
I do not own apt.mopidy.com, so only maintainers of this repository can do that.

**Comment by PanderMusubi** [comment]
OK. Reported request at https://discuss.mopidy.com/t/add-mopidy-somafm-to-dep-repo/809
