### ISSUE TITLE
Offer via apt repository

### ISSUE THREAD

**Issue by PanderMusubi** [AlexandrePTJ/mopidy-somafm#19]
Please offer mopidy-somafm in http://apt.mopidy.com so it can be installed along other Mopidy extensions via apt-get.

**Comment by AlexandrePTJ** [comment]
The answer is the same as #16 .

**Comment by PanderMusubi** [comment]
Oops, sorry for that.

**Comment by jodal** [comment]
Packaging mopidy-somafm is on my todo list.
