### ISSUE TITLE
Improve performance on channel data

### ISSUE THREAD

**Issue by PanderMusubi** [AlexandrePTJ/mopidy-somafm#20]
Please use https://api.somafm.com/channels.xml instead of http://api.somafm.com/channels.xml According to SomaFM management, this one has better performance.

They also told me the information is available in JSON format, see https://api.somafm.com/channels.json but that only as a side note.

**Comment by AlexandrePTJ** [comment]
Using https instead of http will not improve performance but security.
I may add a config key to let user choose anyway.

**Comment by PanderMusubi** [comment]
Sounded strange to me too, perhaps the updates of playing now is a bit quicker available. Well, this was the advice of Soma FM, not sure how they have it set up internally. They advised to switch over to HTTPS completely.

**Comment by PanderMusubi** [comment]
FYI https://github.com/PanderMusubi/online-radio-channels

I have asked SomaFM why https should have better performance. Will keep you updated here.

**Comment by jodal** [comment]
Why not always use HTTPS, irrespective of performance and user choice? The more encrypted traffic on the net, the better.

**Comment by PanderMusubi** [comment]
:+1:

**Comment by PanderMusubi** [comment]
According to SomaFM, the https is a cluster of machines and the http is another stand-alone machine, hence the performance improvement.
