### ISSUE TITLE
Packaged in Debian

### ISSUE THREAD

**Issue by jodal** [AlexandrePTJ/mopidy-somafm#22]
Just a heads up: I just uploaded the mopidy-somafm package to Debian unstable (soon to be part of the next Raspbian, Ubuntu 16.04) and apt.mopidy.com. You might want to update the README accordingly :-)

**Comment by PanderMusubi** [comment]
Yes, it is there. Thanks. This issue may be closed.

**Comment by AlexandrePTJ** [comment]
Thanks @jodal for your contribution
