### ISSUE TITLE
Not all playlists are supported

### ISSUE THREAD

**Issue by PanderMusubi** [AlexandrePTJ/mopidy-somafm#25]
If you try using the XML file https://intergalacticfm.com/channels.xml you will get errors for all playlists

For MP3 the client will run into problems, for AAC you get errors such as:
2016-01-26 21:30:40,196 INFO [1720:StreamBackend-3] mopidy.stream.actor: Unwrapping stream from URI (https://intergalacticfm.com/ifm2-128aac.pls) failed: error downloading URI chunklist.m3u8?wowzasessionid=1904043045

How can these playlists get supported?

**Comment by PanderMusubi** [comment]
Any thoughts on this? KODI supports it with http://addons.kodi.tv/show/plugin.audio.intergalacticfm/ but in https://github.com/clementine-player/Clementine/pull/5243 I think I run into the same problem.

**Comment by AlexandrePTJ** [comment]
I am sorry about that, but this not an issue about this extension.
