### ISSUE TITLE
Mopidy-SomaFM release for Mopidy 3.0

### ISSUE THREAD

**Issue by jodal** [AlexandrePTJ/mopidy-somafm#36]
Mopidy 3.0 final is out now! It would be great if you could release Mopidy-SomaFM as a final release in the near future :-)

**Comment by dreamlayers** [comment]
Mopidy-SomaFM is usable with Python 3.7.3 and Mopidy 3.0.1. Channel listing and playback works. The only problem I've encountered is that channel images don't get displayed, as I described in #37.

**Comment by jodal** [comment]
Among the extensions featured at https://mopidy.com/ext/, Mopidy-SomaFM is now the only remaining one that only has a pre-release with support for Mopidy 3 and Python 3.

It would be nice to have the pre-releases re-released as a final release, just to make it easier for users to install, and so that we can remove the extra instructions for how to install pre-releases from mopidy.com.
