### ISSUE TITLE
Images don't work in Mopidy 3.0

### ISSUE THREAD

**Issue by dreamlayers** [AlexandrePTJ/mopidy-somafm#37]
SomaFMLibraryProvider get_image() doesn't return what Mopidy 3.0 wants. This is easy to fix, using `images = {}` and `images[uri] = [ image ]`.

Unfortunately, that is insufficient. The problem is that track URIs are https:// pls URLs, which have no connection to mopidy-somafm anymore. So, SomaFMLibraryProvider's get_image() function won't be called for the track.

There's still the album, which has its own URI, which is handled by mopidy-somafm, and which can return the proper image after the simple fix to get_image(). But that's not being used when browsing via mopidy-mobile. Furthermore, when a track is added to the tracklist, the connection to the Album created by mopidy-somafm in lookup() is lost. Seems like Mopidy fetches new metadata when adding the pls URL to the playlist.

Edit: As far as I can tell there doesn't seem to be a nice way to fix this. The obvious solution is to give out mopidy-somafm URIs instead of https:// pls URLs, and then implement a playback provider which uses [translate_uri()](https://docs.mopidy.com/en/latest/api/backend/#mopidy.backend.PlaybackProvider.translate_uri). But the return value of translate_uri() must be a stream which can be played directly, not a playlist. Normally [StreamPlaybackProvider uses its own translate_uri()](https://github.com/mopidy/mopidy/blob/302daef92679f0d7e4f5a8952563d0970979522b/mopidy/stream/actor.py#L84) to get the stream URL from the playlist. But there doesn't seem to be any nice way to access that from another playback provider. So, that would involve either hooking into internals or reimplementing StreamPlaybackProvider's _unwrap_stream().

**Comment by adamcik** [comment]
Typically the way to solve this within mopidy is to introduce a somafm uri scheme, e.g. `somafm:beatblender`. If we implemented https://github.com/mopidy/mopidy/issues/696 then you could just have this extension claim `http://somafm.com/` instead. But if you want to fix this now a custom URI scheme is quicker to get going.

**Comment by adamcik** [comment]
Though there might be some nuance in getting Stream to handle the playlist unwrapping in a nice way, while this extension doing the images. So it might not be as simple as just doing the custom scheme?

**Comment by dreamlayers** [comment]
> Though there might be some nuance in getting Stream to handle the playlist unwrapping in a nice way, while this extension doing the images. So it might not be as simple as just doing the custom scheme?

Yes, that is what I'm wondering about now. It doesn't seem like there's some documented official way for one backend to reach another backend like that. I expect I can somehow reach Stream, but it would probably involve using Mopidy internals which I shouldn't be using.

**Comment by adamcik** [comment]
The other option could just be to implement a playback provider for this backend and then return `somafm` uris like are already being used (as I just confirmed). Since you "know" that all the entries in `channels.xml` will be PLS playlists you could just fetch them with requests and use configparser on them to get one of the entries at random. You don't really need the magic mopidy-stream does in trying to detect playlists and unwrapping them.

Looking more at mopidy/mopidy#696 the other option I'm considering is to use the longest prefix match of a backend that has the right provider. In this case you would match for library related calls to http://somafm.com but not playback ones. Which would also solve this, just require at least a Mopidy 3.1 with this new support.

**Comment by dreamlayers** [comment]
With configparser, that's very simple! I implemented it in https://github.com/dreamlayers/mopidy-somafm/tree/images-fix.

I duplicated the "Build requests session" part. Maybe that can be shared but I don't think that's important.

Using the longest prefix match in Mopidy 3.1 seems more elegant, but this works now. Track names still get updated while playing. Also, this should be faster, avoiding unnecessary connections to SomaFM when adding channels to the track list. `mpc add somafm:channel:/groovesalad` is instant while `mpc add https://somafm.com/groovesalad130.pls` takes some time. Another benefit is that changes in settings can now change what format of stream is played even after the channel is added to a playlist.

Let me know if you want a pull request, and if you want some changes, or feel free to take what I wrote as a starting point and do it yourself.

**Comment by morithil** [comment]
Will this fix be released? Otherwise, how can I implement @dreamlayers fix?

**Comment by AlexandrePTJ** [comment]
@dreamlayers Sorry I missed your comment. Yes please, do a PR with your modifications.

**Comment by morithil** [comment]
Awesome, I will await the PR from @dreamlayers  👍
