### ISSUE TITLE
not finding the URI

### ISSUE THREAD

**Issue by leealder** [AlexandrePTJ/mopidy-somafm#38]
I'm getting this trying to tune into SomaFm

 File "/usr/lib/python3/dist-packages/mopidy_somafm/backend.py", line 45, in lookup
Nov 05 21:41:57 raspberrypi mopidy[836]:     channel_name = uri[uri.index("/") + 1 :]

**Comment by AlexandrePTJ** [comment]
Which linux distro do you use ?

**Comment by leealder** [comment]
Raspberry Pi Stretch (lite)

**Comment by AlexandrePTJ** [comment]
Ok, I try to reproduce and then fix it.

**Comment by AlexandrePTJ** [comment]
Did you installed from apt ? I am running a Debian stretch using package from apt and it works fine.

**Comment by leealder** [comment]
Not sure, tried several times with different ways.
Debian stretch for Raspberry Pi ?

**Comment by leealder** [comment]
I am sorry, it seems the problem is in Iris.

**Comment by AlexandrePTJ** [comment]
Ok. No problem.

**Comment by leealder** [comment]
I did get it working on MusicBox. Love SomaFM (wish they made a tee shirt
in my size!)
So great extension!!
